<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Financial Report - {{ $report->start_date }} to {{ $report->end_date }}</title>
    <style>
        @charset "UTF-8";
        body {
            font-family: DejaVu Sans, Arial, sans-serif;
            margin: 0;
            padding: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }
        .header .logo {
            max-height: 80px;
            margin-bottom: 15px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #2c3e50;
            font-weight: bold;
        }
        .header .company-name {
            font-size: 20px;
            font-weight: bold;
            color: #2c3e50;
            margin: 10px 0 5px 0;
        }
        .header .company-address {
            font-size: 12px;
            color: #666;
            margin: 5px 0;
        }
        .header .report-title {
            font-size: 18px;
            font-weight: bold;
            color: #2c3e50;
            margin: 15px 0 5px 0;
        }
        .header p {
            margin: 5px 0;
            color: #666;
            font-size: 12px;
        }
        .summary-section {
            margin-bottom: 30px;
        }
        .summary-table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        .summary-table th,
        .summary-table td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        .summary-table th {
            background-color: #f8f9fa;
            font-weight: bold;
        }
        .summary-table .amount {
            text-align: right;
            font-weight: bold;
        }
        .positive {
            color: #28a745;
        }
        .negative {
            color: #dc3545;
        }
        .breakdown-section {
            margin-bottom: 30px;
        }
        .breakdown-section h3 {
            color: #2c3e50;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
        }
        .breakdown-table {
            width: 100%;
            border-collapse: collapse;
        }
        .breakdown-table th,
        .breakdown-table td {
            padding: 8px 12px;
            text-align: left;
            border-bottom: 1px solid #eee;
        }
        .breakdown-table th {
            background-color: #f8f9fa;
            font-weight: bold;
        }
        .breakdown-table .amount {
            text-align: right;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 12px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        @php
            $logoPath = public_path('Image/logo.jpg');
            $logoExists = file_exists($logoPath);
            if ($logoExists) {
                $logoData = base64_encode(file_get_contents($logoPath));
                $logoMime = mime_content_type($logoPath);
                $logoBase64 = 'data:' . $logoMime . ';base64,' . $logoData;
            }
        @endphp
        @if($logoExists)
            <img src="{{ $logoBase64 }}" alt="United Farmers Association Logo" class="logo">
        @endif
        <div class="company-name">United Farmers Association of Baugo</div>
        <div class="company-address">Baugo, Maasin City, Southern Leyte, 6600, Philippines</div>
        <div class="report-title">Financial Summary Report</div>
        <p>Period: {{ \Carbon\Carbon::parse($report->start_date)->format('F j, Y') }} - {{ \Carbon\Carbon::parse($report->end_date)->format('F j, Y') }}</p>
        <p>Generated by: {{ $report->generatedBy->name ?? 'N/A' }}</p>
        <p>Generated on: {{ $report->created_at->format('F j, Y \a\t g:i A') }}</p>
    </div>

    <div class="summary-section">
        <h2>Income Statement</h2>
        <p style="font-size: 12px; color: #666; margin-bottom: 15px;">This statement shows the company's profitability by detailing revenues and expenses for the period.</p>
        <table class="summary-table">
            <tr>
                <th>Total Revenue</th>
                <td class="amount">&#8369;{{ number_format($report->total_revenue, 2) }}</td>
            </tr>
            <tr>
                <th>Total Expenses</th>
                <td class="amount">&#8369;{{ number_format($report->total_expenses, 2) }}</td>
            </tr>
            <tr>
                <th>Net Income</th>
                <td class="amount">
                    &#8369;{{ number_format($report->net_income, 2) }}
                </td>
            </tr>
        </table>
    </div>

    @if(isset($reportData['expenseBreakdown']) && count($reportData['expenseBreakdown']) > 0)
    <div class="breakdown-section">
        <h3>Expense Breakdown</h3>
        <table class="breakdown-table">
            <thead>
                <tr>
                    <th>Category</th>
                    <th class="amount">Amount</th>
                </tr>
            </thead>
            <tbody>
                @foreach($reportData['expenseBreakdown'] as $category => $amount)
                <tr>
                    <td>{{ ucfirst($category) }}</td>
                    <td class="amount">&#8369;{{ number_format($amount, 2) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endif

    @if(isset($reportData['productionBreakdown']) && count($reportData['productionBreakdown']) > 0)
    <div class="breakdown-section">
        <h3>Operational Summary</h3>
        <p style="font-size: 12px; color: #666; margin-bottom: 10px;">Production data for the reporting period.</p>
        <table class="breakdown-table">
            <thead>
                <tr>
                    <th>Product</th>
                    <th class="amount">Quantity</th>
                </tr>
            </thead>
            <tbody>
                @foreach($reportData['productionBreakdown'] as $product => $quantity)
                <tr>
                    <td>{{ $product }}</td>
                    <td class="amount">{{ number_format($quantity) }} pcs</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endif

    @if($report->admin_notes)
    <div class="breakdown-section">
        <h3>Admin Notes</h3>
        <p>{{ $report->admin_notes }}</p>
    </div>
    @endif

    <div class="footer">
        @if($report->status === 'approved')
        <p>This report was approved on {{ $report->reviewed_at ? \Carbon\Carbon::parse($report->reviewed_at)->format('F j, Y \a\t g:i A') : 'N/A' }}</p>
        @elseif($report->status === 'rejected')
            <p>This report was rejected on {{ $report->reviewed_at ? \Carbon\Carbon::parse($report->reviewed_at)->format('F j, Y \a\t g:i A') : 'N/A' }}</p>
        @else
            <p>This report is pending approval</p>
        @endif
        <p>Report ID: {{ $report->id }}</p>
    </div>
</body>
</html>

