<script setup>
import { Head } from '@inertiajs/vue3';
import TreasurerLayout from '@/Layouts/TreasurerLayout.vue';

const props = defineProps({
    report: Object,
    reportData: Object,
});

const formatCurrency = (value) => `₱${parseFloat(value).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

const printPage = () => {
    window.print();
};
</script>

<template>
    <Head title="Print Financial Report" />

    <TreasurerLayout>
        <template #header>Financial Report - Print View</template>

        <!-- Print Controls (hidden when printing) -->
        <div class="print:hidden mb-6">
            <div class="bg-white p-4 rounded-lg shadow">
                <div class="flex justify-between items-center">
                    <h2 class="text-xl font-bold">Financial Report Print Preview</h2>
                    <button @click="printPage" class="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600">
                        Print Report
                    </button>
                </div>
            </div>
        </div>

        <!-- Report Content -->
        <div class="bg-white p-8 rounded-lg shadow print:shadow-none">
            <!-- Header -->
            <div class="text-center mb-8 border-b-2 border-gray-300 pb-6">
                <h1 class="text-3xl font-bold text-gray-800 mb-2">Financial Summary Report</h1>
                <p class="text-lg text-gray-600 mb-1">
                    Period: {{ new Date(report.start_date).toLocaleDateString() }} - {{ new Date(report.end_date).toLocaleDateString() }}
                </p>
                <p class="text-gray-600">Generated by: {{ report.generated_by?.name || 'N/A' }}</p>
                <p class="text-gray-600">Generated on: {{ new Date(report.created_at).toLocaleDateString() }}</p>
            </div>

            <!-- Financial Summary -->
            <div class="mb-8">
                <h2 class="text-2xl font-bold text-gray-800 mb-4">Financial Summary</h2>
                <div class="overflow-hidden">
                    <table class="w-full border-collapse">
                        <thead>
                            <tr class="bg-gray-50">
                                <th class="border border-gray-300 px-4 py-3 text-left font-semibold">Item</th>
                                <th class="border border-gray-300 px-4 py-3 text-right font-semibold">Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="border border-gray-300 px-4 py-3 font-medium">Total Revenue</td>
                                <td class="border border-gray-300 px-4 py-3 text-right font-bold text-gray-700">
                                    {{ formatCurrency(report.total_revenue) }}
                                </td>
                            </tr>
                            <tr>
                                <td class="border border-gray-300 px-4 py-3 font-medium">Total Expenses</td>
                                <td class="border border-gray-300 px-4 py-3 text-right font-bold text-gray-700">
                                    {{ formatCurrency(report.total_expenses) }}
                                </td>
                            </tr>
                            <tr class="bg-gray-50">
                                <td class="border border-gray-300 px-4 py-3 font-bold">Net Income</td>
                                <td class="border border-gray-300 px-4 py-3 text-right font-bold text-gray-700">
                                    {{ formatCurrency(report.net_income) }}
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

            <!-- Expense Breakdown -->
            <div v-if="reportData?.expenseBreakdown && Object.keys(reportData.expenseBreakdown).length > 0" class="mb-8">
                <h3 class="text-xl font-bold text-gray-800 mb-4">Expense Breakdown</h3>
                <div class="overflow-hidden">
                    <table class="w-full border-collapse">
                        <thead>
                            <tr class="bg-gray-50">
                                <th class="border border-gray-300 px-4 py-3 text-left font-semibold">Category</th>
                                <th class="border border-gray-300 px-4 py-3 text-right font-semibold">Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr v-for="(amount, category) in reportData.expenseBreakdown" :key="category">
                                <td class="border border-gray-300 px-4 py-3">{{ category.charAt(0).toUpperCase() + category.slice(1) }}</td>
                                <td class="border border-gray-300 px-4 py-3 text-right">{{ formatCurrency(amount) }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

            <!-- Production Summary -->
            <div v-if="reportData?.productionBreakdown && Object.keys(reportData.productionBreakdown).length > 0" class="mb-8">
                <h3 class="text-xl font-bold text-gray-800 mb-4">Production Summary</h3>
                <div class="overflow-hidden">
                    <table class="w-full border-collapse">
                        <thead>
                            <tr class="bg-gray-50">
                                <th class="border border-gray-300 px-4 py-3 text-left font-semibold">Product</th>
                                <th class="border border-gray-300 px-4 py-3 text-right font-semibold">Quantity</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr v-for="(quantity, product) in reportData.productionBreakdown" :key="product">
                                <td class="border border-gray-300 px-4 py-3">{{ product }}</td>
                                <td class="border border-gray-300 px-4 py-3 text-right">{{ quantity.toLocaleString() }} pcs</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

            <!-- Admin Notes -->
            <div v-if="report.admin_notes" class="mb-8">
                <h3 class="text-xl font-bold text-gray-800 mb-4">Admin Notes</h3>
                <div class="bg-gray-50 p-4 rounded border">
                    <p class="text-gray-700">{{ report.admin_notes }}</p>
                </div>
            </div>

            <!-- Footer -->
            <div class="mt-12 pt-6 border-t-2 border-gray-300 text-center text-sm text-gray-600">
                <p v-if="report.status === 'approved'">
                    This report was approved on {{ report.reviewed_at ? new Date(report.reviewed_at).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }) + ' at ' + new Date(report.reviewed_at).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' }) : 'N/A' }}
                </p>
                <p v-else-if="report.status === 'rejected'">
                    This report was rejected on {{ report.reviewed_at ? new Date(report.reviewed_at).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }) + ' at ' + new Date(report.reviewed_at).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' }) : 'N/A' }}
                </p>
                <p v-else>
                    This report is pending approval
                </p>
                <p class="mt-2">Report ID: {{ report.id }}</p>
            </div>
        </div>
    </TreasurerLayout>
</template>

<style>
@media print {
    .print\\:hidden {
        display: none !important;
    }
    .print\\:shadow-none {
        box-shadow: none !important;
    }
    body {
        font-size: 12px;
    }
    .bg-gray-50 {
        background-color: #f9fafb !important;
    }
}
</style>
